### ISSUE TITLE
Two keys to make it more user friendly

### ISSUE THREAD

**Issue by pablgonz** [zauguin/install-texlive#1]
Hi Marcel Krüger, first of all thanks a lot for providing this TeX Live installation using actions ...it's great :D

I have observed and tested how it works following the logic of the official LaTeX repositories and I have managed to make it work in mine as well (https://github.com/pablgonz/scontents/actions) with some modifications I like.

I don't know if it will be feasible for you to implement something like (https://github.com/awalsh128/cache-apt-pkgs-action). I have read the comments on the `.yalm` files so I understand (more or less how it works), specifically I would like to:

```yaml
      - name: Generate unique ID
        id: get-id
        run: |
          echo -n ::set-output name=id::
          cat /proc/sys/kernel/random/uuid
      # Actually load the cache. Since we never reuse the key, we need restore-keys
      # to indicate the prefix of our caches. This loads the newest cache with this
      # prefix in the key.
      #
      # If we want to force regeneration of the cache, increase the number after
      # *both* instances of "texlive-v"
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: ~/texlive
          key: texlive2022-v0-${{ steps.get-id.outputs.id }}
          restore-keys: texlive2022-v0-
      - name: Install TeX Live
        uses: zauguin/install-texlive@v1
        with:
          # List the required TeX Live packages in a separate file to allow reuse in
          # different workflows.
          package_file: .github/tl_packages
```

will be simplified to:

```yaml
      - name: Install TeX Live
        uses: zauguin/install-texlive@v1
        with:
          package_file: .github/tl_packages
          version: 1.0
          refresh: true
```

in this case `version: 1.0` would be equivalent to `Generate unique ID` and `Load cache` and the key ` refresh: true` would allow to overwrite the cache (using the same version number).

In this way in `cache.yaml` we would use:

```yaml
      - name: Keep update TeX Live
        uses: zauguin/install-texlive@v1
        with:
          package_file: .github/tl_packages
          version: 1.0
          refresh: true
```

and in `main.yaml` we would use:

```yaml
      - name: Install TeX Live
        uses: zauguin/install-texlive@v1
        with:
          package_file: .github/tl_packages
          version: 1.0
          refresh: false
```

It's just an idea, I know that programming takes time and I don't know if it's feasible (beyond what my mind thinks as I write this :).

Regards
