### ISSUE TITLE
Howto for Pretesting

### ISSUE THREAD

**Issue by koppor** [zauguin/install-texlive#58]
I would like to take part in pretesting.

Is there an easy step-by-step guide?

Alternatively, it would be nice if the installation action would allow for `use_pretest: true` (with default: `false`). In case there is no pre-test, the action should just output a warning and continue as if it was `use_pretest: false`.

---

(for the interested readers: background on pretesting: https://www.tug.org/texlive/pretest.html)

**Comment by koppor** [comment]
Current try:

```yaml
      - name: Switch to pretest TeX Live
        run: |
          set -e
          cd /tmp
          # Source: https://www.tug.org/texlive/mirmon/
          PRETEST_URL=https://www.math.utah.edu/pub/tlpretest/
          wget -q $PRETEST_URL/update-tlmgr-latest.sh
          sh ./update-tlmgr-latest.sh
          tlmgr option repo $PRETEST_URL
          tlmgr update --self
          tlmgr update --all
```

But does not work, because tlpretest has older revision:

```
 tlmgr: Remote database (revision 73948 of the texlive-scripts package)
seems to be older than the local installation (rev 73951 of
texlive-scripts); please use a different mirror and/or wait a day or two.
```

**Comment by koppor** [comment]
It's damn simple: Just use the correct mirror

```yaml
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          package_file: '/tmp/gen/Texlivefile'
          repository: http://ftp.math.utah.edu/pub/tlpretest/
          cache_version: 2
```
