### ISSUE TITLE
Support *both* packages and package-file

### ISSUE THREAD

**Issue by koppor** [zauguin/install-texlive#73]
Real world example: (https://github.com/Witiko/expltools/blob/7b87fea5c27d0b3dfbed482bb3648bf2f77c10e2/.github/workflows/main.yml#L178)

```yaml
        with:
          packages: |
            scheme-basic
            l3build
          package-file: |
            **/DEPENDS.txt
```

I changed it to

```yaml
        with:
          packages: |
            scheme-basic
            l3build
          package_file: explcheck/support/DEPENDS.txt
```

(glob patterns probably don't work)

The action still uses one the first parameter only
